# Generated by Django 4.0.2 on 2025-12-19 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
